//go:build !ignore_autogenerated

/*
SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package eppconfig

import (
	"sigs.k8s.io/gateway-api-inference-extension/apix/config/v1alpha1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointPickerConfig) DeepCopyInto(out *EndpointPickerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = make(v1alpha1.FeatureGates, len(*in))
		copy(*out, *in)
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]v1alpha1.PluginSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SchedulingProfiles != nil {
		in, out := &in.SchedulingProfiles, &out.SchedulingProfiles
		*out = make([]v1alpha1.SchedulingProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SaturationDetector != nil {
		in, out := &in.SaturationDetector, &out.SaturationDetector
		*out = new(SaturationDetectorConfig)
		**out = **in
	}
	if in.DataLayer != nil {
		in, out := &in.DataLayer, &out.DataLayer
		*out = new(v1alpha1.DataLayerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.FlowControl != nil {
		in, out := &in.FlowControl, &out.FlowControl
		*out = new(v1alpha1.FlowControlConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Parser != nil {
		in, out := &in.Parser, &out.Parser
		*out = new(v1alpha1.ParserConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointPickerConfig.
func (in *EndpointPickerConfig) DeepCopy() *EndpointPickerConfig {
	if in == nil {
		return nil
	}
	out := new(EndpointPickerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SaturationDetectorConfig) DeepCopyInto(out *SaturationDetectorConfig) {
	*out = *in
	out.MetricsStalenessThreshold = in.MetricsStalenessThreshold
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SaturationDetectorConfig.
func (in *SaturationDetectorConfig) DeepCopy() *SaturationDetectorConfig {
	if in == nil {
		return nil
	}
	out := new(SaturationDetectorConfig)
	in.DeepCopyInto(out)
	return out
}
